import type { FoodRule, Medication, Period } from "./types";

export const periods: Period[] = ["Morning", "Midday", "Evening", "Bedtime"];
export const foodRules: FoodRule[] = [
  "With food",
  "Empty stomach",
  "With or without food",
];

export const initialMedications: Medication[] = [
  {
    id: "metronidazole-am",
    name: "Metronidazole",
    dose: "0.7 mL",
    period: "Morning",
    food: "With food",
    purpose: "Antibiotic",
    annotation: "Until gone",
    active: true,
  },
  {
    id: "amoxicillin-am",
    name: "Amoxicillin/Clavulanate",
    dose: "1 tablet",
    period: "Morning",
    food: "With food",
    purpose: "Antibiotic",
    annotation: "Until gone",
    active: true,
  },
  {
    id: "prednisone",
    name: "Prednisone",
    dose: "1.5 tablets",
    period: "Morning",
    food: "With or without food",
    purpose: "Anti-inflammatory steroid",
    annotation: "Daily",
    active: true,
  },
  {
    id: "capromorelin",
    name: "Capromorelin",
    dose: "0.8 mL",
    period: "Midday",
    food: "Empty stomach",
    purpose: "Appetite stimulant",
    annotation: "As needed",
    isAsNeeded: true,
    active: true,
  },
  {
    id: "metronidazole-pm",
    name: "Metronidazole",
    dose: "0.7 mL",
    period: "Evening",
    food: "With food",
    purpose: "Antibiotic",
    annotation: "Until gone",
    active: true,
  },
  {
    id: "amoxicillin-pm",
    name: "Amoxicillin/Clavulanate",
    dose: "1 tablet",
    period: "Evening",
    food: "With food",
    purpose: "Antibiotic",
    annotation: "Until gone",
    active: true,
  },
  {
    id: "same",
    name: "SAMe",
    dose: "1 tablet",
    period: "Evening",
    food: "Empty stomach",
    purpose: "Liver protectant",
    annotation: "Daily",
    active: true,
  },
  {
    id: "ondansetron",
    name: "Ondansetron",
    dose: "1 tablet",
    period: "Bedtime",
    food: "With or without food",
    purpose: "Prevent nausea/vomiting",
    annotation: "As needed, every 8-12 hours",
    isAsNeeded: true,
    active: true,
  },
];
